import { useState, useEffect, useRef } from 'react';
import { Loader2, Sparkles } from 'lucide-react';
import { Button, Modal, Textarea, TextDiff } from '../ui';
import { useAppStore } from '../../stores/appStore';
import { updateResumeWithDetails } from '../../services/ai';
import { showToast } from '../../stores/toastStore';

interface ResumeUpdateReviewProps {
  initialDetails: string;
  onClose: () => void;
}

function ResumeUpdateReview({ initialDetails, onClose }: ResumeUpdateReviewProps): JSX.Element {
  const { settings, updateSettings } = useAppStore();
  const [details, setDetails] = useState(initialDetails);
  const [proposedResume, setProposedResume] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const hasAutoGenerated = useRef(false);

  const currentResume = settings.defaultResumeText;
  const hasChanges = proposedResume !== null && proposedResume !== currentResume;

  async function handleGenerate(): Promise<void> {
    setIsGenerating(true);
    try {
      setProposedResume(await updateResumeWithDetails(currentResume, details));
    } catch (error) {
      console.error('Failed to update resume:', error);
      showToast(error instanceof Error ? error.message : 'Failed to update resume', 'error');
    } finally {
      setIsGenerating(false);
    }
  }

  // When opened with details already supplied (e.g., by the agent), generate right away
  useEffect(() => {
    if (initialDetails.trim() && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleDetailsChange(e: React.ChangeEvent<HTMLTextAreaElement>): void {
    setDetails(e.target.value);
  }

  async function handleSave(): Promise<void> {
    if (proposedResume === null) return;
    await updateSettings({ defaultResumeText: proposedResume });
    showToast('Resume updated', 'success');
    onClose();
  }

  return (
    <Modal isOpen onClose={onClose} title="Update Resume with AI" size="full">
      <div className="flex flex-col h-full">
        <div className="p-4 space-y-3 border-b border-border">
          <Textarea
            id="resume-update-details"
            label="What's new?"
            placeholder="e.g., Started as Senior Product Manager at Acme in March 2026. Leading the payments team of 8, launched instant payouts which grew volume 30%..."
            value={details}
            onChange={handleDetailsChange}
            rows={5}
          />
          <div className="flex items-center justify-between gap-4">
            <p className="text-xs text-foreground-muted">
              Only what you write here is added. Your resume isn't changed until you save.
            </p>
            <Button
              variant={proposedResume === null ? 'primary' : 'secondary'}
              onClick={handleGenerate}
              disabled={isGenerating || !details.trim()}
            >
              {isGenerating ? (
                <Loader2 className="w-4 h-4 mr-1 animate-spin" />
              ) : (
                <Sparkles className="w-4 h-4 mr-1" />
              )}
              {proposedResume === null ? 'Generate update' : 'Regenerate'}
            </Button>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-4">
          {proposedResume === null ? (
            <p className="text-sm text-foreground-muted text-center py-16">
              {isGenerating
                ? 'Updating your resume...'
                : 'Describe your new role or achievements above, then generate to preview the changes.'}
            </p>
          ) : hasChanges ? (
            <TextDiff original={currentResume} updated={proposedResume} />
          ) : (
            <p className="text-sm text-foreground-muted text-center py-16">
              The AI didn't change anything. Try adding more detail above and regenerate.
            </p>
          )}
        </div>

        <div className="flex justify-end gap-2 p-4 border-t border-border">
          <Button variant="ghost" onClick={onClose}>
            Cancel
          </Button>
          <Button onClick={handleSave} disabled={!hasChanges || isGenerating}>
            Save to resume
          </Button>
        </div>
      </div>
    </Modal>
  );
}

export function ResumeUpdateModal(): JSX.Element | null {
  const { resumeUpdateDetails, closeResumeUpdate } = useAppStore();

  if (resumeUpdateDetails === null) return null;

  return <ResumeUpdateReview initialDetails={resumeUpdateDetails} onClose={closeResumeUpdate} />;
}
